version: "2"
services:
  gekko:
      image: ${REGISTRY}trydirect/gekko:latest
      build: .
      command: ['bash', '-c', 'node gekko --ui']
      #entrypoint: /usr/bin/supervisord -c /etc/supervisor/supervisord.conf -n
      volumes:
          #- ./src:/var/www/html
          - ./configs/gekko/config.js:/var/www/html/web/vue/dist/UIconfig.js
          - /var/www/html
      ports:
          - "3000:3000"

  nginx:
    image: ${REGISTRY}trydirect/nginx:latest
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./configs/nginx/conf.d/gekko.conf:/etc/nginx/sites-available/default
      - ./configs/supervisord/nginx.conf:/etc/supervisor/conf.d/nginx.conf
    links:
      - gekko
    depends_on:
      - gekko
    entrypoint: /usr/bin/supervisord -c /etc/supervisor/supervisord.conf -n
